#!/bin/bash

#use strict;
batval=`cat /sys/class/power_supply/BAT1/capacity`

#my $batval;
#open(BATTERY, "cat /sys/class/power_supply/BAT1/capacity")or die;
#$batval = <BATTERY>;
#close(BATTERY);
#print "$batval\n"
if test $batval -le 20; then
		echo  
elif test $batval -le 40 && test $batval -gt 20; then
		echo 
elif test $batval -le 60 && test $batval -gt 40; then
		echo 
elif test $batval -le 80 && test $batval -gt 60; then
		echo  
else
		echo 
fi


